### ISSUE TITLE
"Maximum call stack size exceeded" For Android Http

### ISSUE THREAD

**Issue by jprsfyy** [mlaval/angular-react-native-seed#9]
"Maximum call stack size exceeded" For Android Http, then debug js Remotely is right.
ios is right.
code:
 this.http.get('https://en.wikipedia.org/w/api.php?format=json&action=query&generator=allpages&gaplimit=10')
        .subscribe(data => {
          this.resMassage = data.text();
        });

**Comment by mlaval** [comment]
Solved after migrating to Angular 4.x, see 40f8e097d79df0ae5641f4c111278b428f2909dc
